cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path('add_videogame/<str:videogame_name>/', add_videogame, name='add_videogame'),
    path('add_dlc/<str:dlc_name>/', add_dlc, name='add_dlc'),
    path('add_package/<str:package_name>/', add_package, name='add_package'),

    path('remove_videogame/<str:videogame_name>/', remove_videogame, name="remove_videogame"),
    path('remove_dlc/<str:dlc_name>/', remove_dlc, name="remove_dlc"),
    path('remove_package/<str:package_name>/', remove_package, name="remove_package"),

    path('decrease_videogame/<str:videogame_name>/', decrease_videogame , name="decrease_videogame"),
    path('decrease_dlc/<str:dlc_name>/', decrease_dlc , name="decrease_dlc"),
    path('decrease_package/<str:package_name>/', decrease_package , name="decrease_package"),

    path('clear_videogame/', clear_cart_videogame , name='clear_cart_videogame'),
    path('clear_dlc/', clear_cart_dlc , name='clear_cart_dlc'),
    path('clear_package/', clear_cart_package , name='clear_cart_package'),

    path('decrease_product/<str:product_name>/', decrease_cart, name= 'decrease_product'),
    path('increase_product/<str:product_name>/', increase_cart, name= 'increase_cart'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import login #para login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('',include('gde.urls')),
    path('cart/',include('cart.urls')),
    path('accounts/',include('django.contrib.auth.urls')), #para login
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),

]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

gde/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from .views import *
from .decorators import allowed_users
from django.contrib.auth.decorators import login_required
#app_name = 'gde'

urlpatterns = [

	path('password_change/', auth_views.PasswordChangeView.as_view(), name= 'password_change'),
	path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name= 'password_change_done'),
	path('password_reset/',auth_views.PasswordResetView.as_view(), name='password_reset'),
	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

	path('videogames/', login_required(VideogameList_view.as_view()), name="videogames"),
	path('packages/', PackageList_view.as_view(), name="packages"),	
	path('dlcs/', DlcList_view.as_view(), name="dlcs"),

	path('videogames/<str:pk>/', VideogameDetail_view.as_view(), name="videogame_detail"),
	path('packages/<str:pk>/', PackageDetail_view.as_view(), name="package_detail"),
	path('dlcs/<str:pk>/', DlcDetail_view.as_view(), name="dlc_detail"),

	path('videogames/<str:pk>/delete/', VideogameDelete_view.as_view(), name="videogame_delete"),
	path('packages/<str:pk>/delete/', PackageDelete_view.as_view(), name="package_delete"),
	path('dlcs/<str:pk>/delete/', DlcDelete_view.as_view(), name="dlc_delete"),

	path('videogames/<str:pk>/update/', VideogameUpdate_view.as_view(), name="videogame_update"),
	path('packages/<str:pk>/update/', PackageUpdate_view.as_view(), name="package_update"),
	path('dlcs/<str:pk>/update/', DlcUpdate_view.as_view(), name="dlc_update"),

	path('videogame/new/', VideogameCreate_view.as_view(), name= "videogame_create"),
	path('package/new/', PackageCreate_view.as_view(), name= "package_create"),
	path('dlc/new/', DlcCreate_view.as_view(), name= "dlc_create"),

	path('',views.main_menu, name=""),
	path('store/', views.store, name='store'),
	path('store/videogame/', list_videogame , name= "list_videogame"),
	path('store/dlc/', list_dlc_dic , name= "list_dlc_dic"),
	path('store/package/', list_package , name= "list_package"),


	path('login/', auth_views.LoginView.as_view(), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),

	path('', include('django.contrib.auth.urls')),
	
	path('register_store/', views.register_store, name= 'register_store'),
	path('register_dispatcher/', views.register_dispatcher, name='register2'),
	path('register_admin/', views.register_admin, name= 'register_admin'),
	
	path('edit_admin/', views.edit_admin, name= 'edit_admin'),	
	path('edit_store/', views.edit_store, name= 'edit_store'),
	path('edit_dispatcher/', views.edit_dispatcher, name= 'edit_dispatcher'),

	path('delivery/list_orders/', DeliveryList_view.as_view(), name= 'list_orders'),
	path('delivery/list_orders/<str:pk>/', DeliveryDetail_view.as_view(), name="detail_order"),
	path('delivery/list_orders/<str:pk>/confirm', DeliveryConfirm_view.as_view(), name="confirm_order"),
	]

order/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('process_order/', process_order, name='process_order'),
]

gde/models.py
from django.db import models

from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class PackagesManager(models.Manager):
	def get_queryset(self):
		return super(PackagesManager, self).get_queryset()
class RandomManager(models.Manager): 
    def get_query_set(self): 
     return super(RandomManager, self).get_queryset()


class GamesManager(models.Manager):
	def get_queryset(self):
		return super(GamesManager,self).get_queryset()
class DlcManager(models.Manager):
	def get_queryset(self):
		return super(DlcManager,self).get_queryset()
class Category(models.Model):
	category_name= models.CharField(max_length= 20, blank= False, unique= True)
	def __str__(self):
	    return self.category_name

class Language(models.Model):
    language= models.CharField(max_length= 50, unique= True)
    def __str__(self):
        return self.language

class Genre(models.Model):
    genre=models.CharField(max_length= 50, unique= True)
    def __str__(self):
        return self.genre


class Format(models.Model):
    formats= models.CharField(max_length= 50, unique= True)
    def __str__(self):
        return self.formats

class Platform(models.Model):
	platform= models.CharField(max_length= 50, unique= True)
	
	def __str__(self):
		return self.platform


class Videogame(models.Model):
	videogame_name= models.CharField(primary_key= True, max_length= 50)
	RATING_CHOICES=(
	('Early childhood', 'EC'), 
	('Every one','E'), ('Every one 10+', 'E10+'), ('Teen', 'T'), 
	('Mature', 'M'), ('Rating Pending', 'RP'), ('Adults', 'A')
	)
	ENGINE_CHOICES=(('Unity', 'Unity'),('Unreal', 'Unreal'), ('GameMaker', 'GameMaker'),
		('Godot', 'Godot'), ('AppGameKit', 'AppGameKit'), ('CryEngine', 'CryEngine'), 
		('Amazon lumberyard','Amazon lumberyard'), ('RPG Maker', 'RPG Maker'), 
		('Lib GDX', 'Lib GDX')
	)
	rating= models.CharField(max_length=20, choices= RATING_CHOICES, default= 'Rating Pending')
	release_date= models.DateField(blank= False)
	engine= models.CharField(max_length=50, choices= ENGINE_CHOICES, blank= False)
	production_cost= models.DecimalField(decimal_places= 2, max_digits= 18, blank= False)
	unit_price= models.DecimalField(decimal_places= 2, max_digits= 18, blank= False)
	administrator= models.ForeignKey(User, on_delete= models.PROTECT)
	category= models.ForeignKey(Category, on_delete= models.PROTECT, default= 2, editable= False)
	genre= models.ManyToManyField(Genre)
	formats= models.ManyToManyField(Format)
	platform= models.ManyToManyField(Platform)
	language= models.ManyToManyField(Language)
	photo= models.ImageField(upload_to='videogame/%Y/%m/%d/', blank= True)
	def get_absolute_url(self):
		return reverse('videogame_detail', kwargs={'pk':self.videogame_name})
	def __str__(self):
		return self.videogame_name
	objects = models.Manager()
	show = GamesManager()
	

class Dlc(models.Model):
	dlc_name= models.CharField(primary_key= True, max_length= 50)
	videogame=  models.ForeignKey(Videogame, on_delete= models.CASCADE)
	Release_date= models.DateField()
	unit_price = models.DecimalField(decimal_places=2, max_digits=18, blank= False)
	administrator = models.ForeignKey(User, on_delete=models.PROTECT)
	category = models.ForeignKey(Category, on_delete=models.PROTECT, default= 3, editable= False)
	photo= models.ImageField(upload_to='dlc/%Y/%m/%d/', blank= True)
	def get_absolute_url(self):
		return reverse('dlc_detail', kwargs={'pk':self.dlc_name})
	def __str__(self):
		return self.dlc_name
	objects = models.Manager()
	show = DlcManager()
class Package(models.Model):
	package_name= models.CharField(primary_key= True, max_length= 50)
	unit_price= models.DecimalField(decimal_places= 2, max_digits= 18, blank= False)
	administrator= models.ForeignKey(User, on_delete= models.PROTECT)
	category= models.ForeignKey(Category, on_delete= models.PROTECT, default= 1, editable= False)
	videogames= models.ManyToManyField(Videogame)
	photo= models.ImageField(upload_to='package/%Y/%m/%d/', blank= True)
	objects = models.Manager()
	show = PackagesManager()
	
	def __str__(self):
		return self.package_name
	def get_absolute_url(self):
		return reverse('package_detail', kwargs={'pk':self.package_name})
class Shopping_cart(models.Model):
    expiration_date= models.DateField()
    total= models.FloatField()
    def __str__(self):
        return 'El carro expira: {0}'.format(self.expiration_date)
class Shopping_cart_packages(models.Model):
	class Meta:
		unique_together = (('cart', 'package'),)
	cart= models.ForeignKey(Shopping_cart, on_delete= models.CASCADE)
	package=models.ForeignKey(Package, on_delete= models.PROTECT)
	units= models.IntegerField(blank= False)
	def __str__(self):
		return self.package
class Shopping_cart_videogames(models.Model):
	class Meta:
		unique_together = (('cart', 'videogame'),)
	cart= models.ForeignKey(Shopping_cart, on_delete= models.CASCADE)
	videogame=models.ForeignKey(Videogame, on_delete= models.PROTECT)
	units= models.IntegerField(blank= False)
	def __str__(self):
		return self.videogame
class Shopping_cart_dlc(models.Model):
	class Meta:
		unique_together = (('cart', 'dlc'),)
	cart= models.ForeignKey(Shopping_cart, on_delete= models.CASCADE)
	dlc=models.ForeignKey(Dlc, on_delete= models.PROTECT)
	units= models.IntegerField(blank= False)
	def __str__(self):
		return self.dlc

class Dispatcher(models.Model):
	BLOOD_CHOICES=(
		('A', 'A'), ('B', 'B'),('AB', 'AB'),('O', 'O')
	)
	RH_CHOICES=(
		('+', '+'), ('-', '-')
		)
	user= models.OneToOneField(User, primary_key= True, on_delete= models.CASCADE)
	telephone= models.CharField(blank= False, unique= True, max_length= 20)
	plate= models.CharField(blank=False, unique=True, max_length= 10)
	weight= models.DecimalField(decimal_places=2, max_digits=10, blank= False)
	height= models.DecimalField(decimal_places=2, max_digits=10, blank= False)
	blood_type= models.CharField(max_length= 20, blank= False, choices= BLOOD_CHOICES)
	rh_type= models.CharField(max_length= 20, blank= False, choices= RH_CHOICES)
	photo= models.ImageField(upload_to='users/%Y/%m/%d/', blank= True)
	def __str__(self):
		return str(self.user)
	objects = models.Manager()  
	randoms = RandomManager() 
		
class Store_location(models.Model):
	city= models.CharField(max_length= 50)
	country= models.CharField(blank= False, max_length= 50)
	state= models.CharField(max_length=20, blank= False)
	class Meta:
		unique_together = (('city', 'country'),)
	def __str__(self):
		return "{0} ({1})".format(self.city, self.country)
class Store(models.Model):
    
	user= models.OneToOneField(User, primary_key= True, on_delete= models.CASCADE)
	street_number= models.CharField(max_length= 50, blank= False)
	street_name= models.CharField(blank= False, max_length= 50)
	city= models.ForeignKey(Store_location, on_delete= models.PROTECT)
	phone = models.CharField(max_length= 20, blank= False)
	photo= models.ImageField(upload_to='users/%Y/%m/%d/', blank= True)
	def __str__(self):
		return str(self.user)
class Checkout(models.Model):
	dispatcher= models.ForeignKey(Dispatcher, on_delete= models.PROTECT)
	Delivery_date= models.DateField()
	store=models.ForeignKey(Store, on_delete= models.PROTECT)
	cart= models.OneToOneField(Shopping_cart, on_delete= models.CASCADE)
	def __str__(self):
		return "Su domiciliario es {0}".format(self.dispatcher)	

gde/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Store, Dispatcher
from django.contrib.auth.forms import UserCreationForm
class UserRegistrationForm(UserCreationForm):
    email= forms.EmailField(required= True)
    first_name= forms.CharField(max_length=30, label= 'Store name')
    class Meta:
        model= User
        fields= ['username', 'email', 'first_name', 'password1', 'password2']
    def save(self, commit= True):
        user= super().save(commit= False)
        user.email= self.cleaned_data['email']
        
        user.first_name= self.cleaned_data['first_name']
        if commit:
            user.save()
        return user
class UserRegistrationFormStore(forms.ModelForm):
    class Meta:
        model= Store
        fields=['street_number', 'street_name', 'city', 'phone', 'photo']
class UserRegistrationForm2(UserCreationForm):
    email= forms.EmailField(required= True)
    first_name= forms.CharField(max_length=30, label= 'First name')
    last_name= forms.CharField(max_length=30, label= 'Last name')
    class Meta:
        model= User
        fields= ['username', 'email', 'first_name','last_name', 'password1', 'password2']
    def save(self, commit= True):
        user= super().save(commit= False)
        user.email= self.cleaned_data['email']
        
        user.first_name= self.cleaned_data['first_name']
        user.last_name= self.cleaned_data['last_name']
        if commit:
            user.save()
        return user
class UserRegistrationFormDispatcher(forms.ModelForm):
    class Meta:
        model= Dispatcher
        fields=['telephone', 'plate', 'weight', 'height', 'blood_type', 'rh_type', 'photo']
class UserRegistrationForm3(UserCreationForm):
    class Meta:
        model= User
        fields= ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
class StoreEditForm(forms.ModelForm):
    class Meta:
        model= User
        labels= {
            'first_name': 'Store name'
        }
        fields= ['first_name', 'email']
class StoreEditForm2(forms.ModelForm):
    class Meta:
        model= Store
        fields= ['photo', 'phone', 'city', 'street_name', 'street_number']
class DispatcherEditForm(forms.ModelForm):
    class Meta:
        model = User
        labels={
            'first_name': 'First name',
            'last_name': 'Last name'
        }
        fields= ['email', 'first_name','last_name']
class DispatcherEditForm2(forms.ModelForm):
    class Meta:
        model= Dispatcher
        fields=['telephone', 'plate', 'weight', 'height', 'blood_type', 'rh_type', 'photo']
class AdminEditForm(forms.ModelForm):
    class Meta:
        model = User
        labels={
            'first_name': 'First name',
            'last_name': 'Last name'
        }
        fields= ['email', 'first_name','last_name']

order/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.views.generic.list import ListView
from django.views.generic import DetailView
from .models import *
from gde.models import *
from cart.cart import Cart
import random

# Create your views here.

@login_required
def process_order(request):
    order = Order.objects.create(user = request.user, dispatcher= Dispatcher.randoms.all()[random.randint(0, len(Dispatcher.randoms.all())-1)])
    cart = Cart(request)
    order_lines = list()
    for key, value in cart.cart.items():
        order_lines.append(
            OrderLine(
                product=key,
                quantity=value["quantity"],
                order=order,
                price=value["price"]
            )
        )

    OrderLine.objects.bulk_create(order_lines)
    send_order_email(
        order =order,
        order_lines = order_lines,
        username = request.user.username,
        user_email = request.user.email,
        dispatcher= order.dispatcher,
    )

    cart.clear()
    messages.success(request, "Order create successfully")
    return redirect("list_videogame")

def send_order_email(**kwargs):
    subject = "Thank you for your order"
    html_message = render_to_string("Order.html", {
        "order": kwargs.get("order"),
        "order_lines": kwargs.get("order_lines"),
        "username": kwargs.get("username"),
        "dispatcher": kwargs.get("dispatcher")
    })
    plain_message = strip_tags(html_message)
    from_email = "game.designer.enterprise@gmail.com"
    to = kwargs.get("user_email")
    send_mail(subject, plain_message, from_email, [to], html_message=html_message)

templates/Order.html
<!DOCTYPE html>
{% load cart_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Thank you</title>
    <style>
      #order {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }

      #order td, #order th {
        border: 1px solid #ddd;
        padding: 8px;
      }

      #order tr:nth-child(even){background-color: #f2f2f2;}

      #order tr:hover {background-color: #ddd;}

      #order th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #1b1e21;
        color: white;
      }

      #order_lines {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }

      #order_lines td, #order_lines th {
        border: 1px solid #ddd;
        padding: 8px;
      }

      #order_lines tr:nth-child(even){background-color: #f2f2f2;}

      #order_lines tr:hover {background-color: #ddd;}

      #order_lines th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #721c24;
        color: white;
      }
  </style>
  </head>
  <body>
  <p>HI {{ username }},</p>
  <p>Thank you for ordering, below are the details.</p>
  <p>
    Your dispatcher is {{dispatcher.user.first_name}} {{dispatcher.user.last_name}}
  </p>
  <h2>order information</h2>
  <table id="order">
      <thead>
          <tr>
              <th>ID</th>
              <th>Total</th>
              <th>Date</th>
          </tr>
      </thead>
      <tbody>
          <tr>
              <td>{{ order.id }}</td>
              <td>{{ order.total|money_format:"$" }}</td>
              <td>{{ order.created_at|date:'d/m/Y H:i' }}</td>
          </tr>
      </tbody>
  </table>
  <hr />
  <h2>Order lines</h2>
  <table id="order_lines">
      <thead>
          <tr>
              <th>Product</th>
              <th>quantity</th>
              <th>unit price</th>
              <th>total</th>
          </tr>
      </thead>
      <tbody>
          {% for order_line in order_lines %}
             <tr class="text-center">
                  <td>{{ order_line.product }}</td>
                  <td>{{ order_line.quantity }}</td>
                  <td>{{ order_line.price|money_format:"$" }}</td>
                  <td>{{ order_line.price|multiply:order_line.quantity|money_format:"$" }}</td>
              </tr>
          {% endfor %}
      </tbody>
  </table>
  </body>
</html>

templates/list_dlc_dic.html
{% extends 'tienda.html' %}

{% load cart_tags %}

{% block title %} Videogames {% endblock %}

{% block content %}
<style>
  body{
    color: #fff;

  }
</style>
  <div class="row">

    <div class="col-9">
      <div class="row">
        {% for dlc in dlcs %}
          <div class="col-md-3 col-sm-12 col-lg-4" style="margin-top=10px;">
            <div class="card" style="width:100%;">
              <img src="{{ dlc.photo.url }}" alt="{{ dlc.dlc_name }}" class="card-img-top" />
              <h5 class="card-title"> {{dlc.dlc_name }} </h5>
              <p class="card-text"> Designed for: {{ dlc.videogame }}</p>
              <p class="card-text">{{ dlc.unit_price|money_format:"$" }}</p>
            </div>
            <div class="card-footer text-center">
              <a href="{% url 'cart:add_dlc' dlc.dlc_name %}" class="btn btn-success">Add to cart</a>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>

    <div class="col-3">
      {% include "widget_cart_dlc.html" %}
    </div>

  </div>
{% endblock %}

templates/register2.html
{% load static %}
<!Doctype html>
<html class="no-js" lang="en">
<head>
  <link rel="stylesheet" href="{% static 'register_store.css' %}">
  <title>register_disp</title>
</head>
<body>
  <div class="form-box">
    <h1>Create Dispatcher</h1>
    {%if user_form.errors or dispatcher_form.errors %}
      <p>Error. Please try again</p>
    {% endif %}
    <form method= 'post' action ="" enctype="multipart/form-data">
      <input type="text" name="username" maxlength="150" autofocus="" placeholder="username" required="" id="id_username">
      <input type="email" name="email" required="" id="id_email" placeholder="email">
      <input type="text" name="first_name" maxlength="30" required="" id="id_first_name" placeholder="first_name">
      <input type="text" name="last_name" maxlength="30" required="" id="id_last_name" placeholder="last_name">
      <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1" placeholder="password">
      <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2" placeholder="Confirm_password">
      <input type="text" name="telephone" maxlength="20" required="" id="id_telephone" placeholder="Phone">
      <input type="text" name="plate" maxlength="10" required="" id="id_plate" placeholder="plate">
      <input type="number" name="weight" step="0.01" required="" id="id_weight" placeholder="weight">
      <input type="number" name="height" step="0.01" required="" id="id_height" placeholder="height">
      <div class="select">
        <select name="blood_type" required="" id="id_blood_type"><option value="" selected="">---Blood type---</option><option value="A">A</option><option value="B">B</option><option value="AB">AB</option><option value="O">O</option></select>
        <select name="rh_type" required="" id="id_rh_type"><option value="" selected="">---Rh type---</option><option value="+">+</option><option value="-">-</option></select>
      </div>
      <div class="form-box-select">
        <input type="file" name="photo" accept="image/*" placeholder="Photo" class="clearablefileinput" id="id_photo">
        <label for="id_photo">Choose profile pic</label>
      </div>
      {% csrf_token %}
      <p><input type="submit" value="Crete an account"></p>
    </form>
  </div>
  </body>
  </html>

templates/register_store33.html
{% load static %}
{% load crispy_forms_tags %}
<!Doctype html>
<html class="no-js" lang="en">
<head>
  <link rel="stylesheet" href="{% static 'register_store.css' %}">
  <title>register</title>
</head>
<body>
  <div class="form-box">
    <h1>Create</h1>
    <form method= 'post' action ="" enctype="multipart/form-data">
      <div id="div_id_username" class="control-group">
        <input type="text" name="username" maxlength="150" placeholder="Username "autofocus="" class="textinput textInput" required="" id="id_username">
      </div>
      <div id="div_id_email" class="control-group">
        <input type="email" name="email" class="emailinput" placeholder="email" required="" id="id_email">
      </div>
      <div id="id_first_name" class="control-group">
        <input type="text" name="first_name" placeholder="Store name" maxlength="30" class="textinput textInput" required="" id="id_first_name">
      </div>
      <div id="id_password1" class="control-group">
        <input type="password" name="password1" autocomplete="new-password" placeholder="Password" class="textinput textInput" required="" id="id_password1">
      </div>
      <div id="id_password2" class="control-group">
        <input type="password" name="password2" autocomplete="new-password" placeholder="Confirm_password" class="textinput textInput" required="" id="id_password2">
      </div>
      {% csrf_token %}
      <div id="div_id_street_number" class="control-group">
        <input type="text" name="street_number" placeholder="Street number" maxlength="50" class="textinput textInput" required="" id="id_street_number">
      </div>
      <div id="div_id_street_name" class="control-group">
        <input type="text" name="street_name" placeholder="Street name" maxlength="50" class="textinput textInput" required="" id="id_street_name">
      </div>
      <div id="div_id_phone" class="control-group">
        <input type="text" name="phone" maxlength="20" placeholder="Phone" class="textinput textInput" required="" id="id_phone">
      </div>
      <div id="div_id_city" class="control-group">
        <select name="city" class="select" required="" id="id_city"> <option value="" selected="">---city---</option> <option value="1">Pasadena (USA)</option> <option value="2">Portland (USA)</option> <option value="3">Seattle (USA)</option> <option value="4">Miami (USA)</option> <option value="5">Pheonix (USA)</option> <option value="6">Santa Cruz (USA)</option> <option value="7">New York (USA)</option> <option value="8">Andalusia (USA)</option> <option value="9">North Hollywood (USA)</option></select>
      </div>
      <div id="div_id_photo" class="control-group">
        <input type="file" name="photo" accept="image/*" placeholder="Photo" class="clearablefileinput" id="id_photo">
        <div class="form-box-select">
          <label for="id_photo">Choose profile pic</label>
        </div>
      </div>
      <input type="submit" value="Create">
    </form>
  </div>
  </body>
  </html>

templates/widget_cart_dlc.html
{% load cart_tags %}
<table class="table table-bordered">
  <thead>
    <tr>
      <th colspan="3" class="text-center">
        Shopping cart
      </th>
    </tr>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% if request.session.cart.items %}
      {% for key, value in request.session.cart.items %}
        <tr class="text-center">
          <td>{{ key }}</td>
          <td>{{ value.quantity }}</td>
          <td>
            <a href="{% url 'cart:decrease_product' key %}" class="ml-2 btn-sm btn btn-danger"> - </a>
            <a href="{% url 'cart:increase_cart' key %}" class="btn btn-sm btn-success"> + </a>
                Total {{ value.price|multiply:value.quantity|money_format:"$" }}    .
          </td>
        </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td colspan="3">
          <div class="alert alert-danger text-center">
            You don't Have products in the shopping cart
          </div>
        </td>
      </tr>
    {%  endif %}
  </tbody>
  <tfoot>
    <tr>
      <td colspan="3">
        Total: {{ cart_total_amount|money_format:"$" }}
      </td>
    </tr>
    {% if request.session.cart.items %}
      <tr>
        <td colspan="3">
          <a href="{% url 'process_order' %}" class="btn btn-success">Checkout</a>
        </td>
      </tr>
    {% endif %}
  </tfoot>
</table>